{
  parserClass="com.ky_proj.ij_kotlin_test.parser.SimpleParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Simple"
  psiImplClassSuffix="Impl"
  psiPackage="com.ky_proj.ij_kotlin_test.psi"
  psiImplPackage="com.ky_proj.ij_kotlin_test.psi.impl"

  elementTypeHolderClass="com.ky_proj.ij_kotlin_test.psi.SimpleTypes"
  elementTypeClass="com.ky_proj.ij_kotlin_test.psi.SimpleElementType"
  tokenTypeClass="com.ky_proj.ij_kotlin_test.psi.SimpleTokenType"
}

simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY